package com.photoselectortoolbox.domain.guidance

import com.photoselectortoolbox.domain.curation.DeferredDeletion
import com.photoselectortoolbox.domain.format.SelectionActionLabels
import com.photoselectortoolbox.domain.interaction.FilingAction
import com.photoselectortoolbox.domain.interaction.SelectorShortcut

/**
 * The wording of every one-time explanation, built from the user's *current*
 * settings.
 *
 * The controls on this screen are all labelled, so this product needs far fewer
 * explanations than a gesture-first one: a hint earns its place only where the
 * **effect is invisible**. Filing a frame is the clearest case — the photograph
 * leaves the centre of the screen and nothing says where it went — and the same
 * is true of a deferred delete (nothing has touched the disk yet) and of
 * maximise (nothing on screen says a second press comes back).
 *
 * Two rules hold every string here together:
 *
 * 1. **Nothing is a constant that depends on a setting.** The filing verb, the
 *    destination folder, whether RAW and JPEG are sorted, the undo window and
 *    every key name are read from the configuration or from the binding
 *    declaration. A hint that says "moved" under a copy configuration is the
 *    same defect as a shortcut sheet that advertises an unbound key.
 * 2. **The wording says what happens to the file.** "Keep", "Save" and
 *    "Favourite" are prohibited by REQUIREMENTS §2 — they describe a feeling,
 *    and under a move configuration they are simply false. A unit test asserts
 *    the euphemisms never appear, mirroring the one guarding
 *    [com.photoselectortoolbox.domain.format.SelectionActionLabels].
 *
 * Kept free of Compose and Android types so all of it is unit-testable.
 */
object SelectorHintText {

    /** The undo window, stated in the same seconds the countdown line drains. */
    private val UNDO_WINDOW_SECONDS = DeferredDeletion.UNDO_WINDOW_MILLIS / 1000

    /**
     * The heading of the explanation.
     *
     * [selectionFolderName] is the *Storage* setting. The filing heading is the
     * same sentence the snackbar shows, so it is generated by
     * [SelectionActionLabels.confirmation] rather than written twice — the two
     * appear on screen together, and the whole point of the 2026-08-08 fix is
     * that they cannot disagree about where the photograph went.
     */
    fun title(
        hint: SelectorHint,
        filingAction: FilingAction,
        selectionFolderName: String = FilingAction.DEFAULT_SELECTION_FOLDER,
    ): String = when (hint) {
        SelectorHint.FILING -> SelectionActionLabels.confirmation(filingAction, selectionFolderName)
        SelectorHint.DELETE_UNDO -> "Deleted — for $UNDO_WINDOW_SECONDS seconds"
        SelectorHint.MAXIMISE -> "One frame, full size"
        SelectorHint.SCORES -> "Scores are on the frames"
        SelectorHint.TOUR -> "The selector"
    }

    /**
     * The body of the explanation.
     *
     * [selectionFolderName] and [sortingEnabled] are the *Storage* settings, so
     * the filing hint names the folder the photograph is actually in rather
     * than the default one.
     */
    fun message(
        hint: SelectorHint,
        filingAction: FilingAction,
        selectionFolderName: String,
        sortingEnabled: Boolean,
    ): String = when (hint) {
        SelectorHint.FILING -> {
            val folder = FilingAction.selectionFolderOrDefault(selectionFolderName)
            val other = filingAction.other
            buildString {
                append("The file is in \"")
                append(folder)
                append("\", inside the shoot folder.")
                if (sortingEnabled) append(" RAW and JPEG are sorted into subfolders.")
                append(" ")
                append(other.shortcut)
                append(" ")
                append(thirdPerson(other))
                append(" instead.")
            }
        }

        SelectorHint.DELETE_UNDO ->
            "Nothing has been written to disk yet. UNDO in the bar at the bottom puts the " +
                "frame back for $UNDO_WINDOW_SECONDS seconds; after that it is deleted for real."

        SelectorHint.MAXIMISE ->
            "${SelectorShortcut.ESCAPE.input}, or the same number again, returns to comparing " +
                "all three. The badge on the frame does the same."

        SelectorHint.SCORES ->
            "Each bar is that metric's score, normalised so longer is always better — whichever " +
                "way the raw number runs. Legend in the sidebar names the icons."

        SelectorHint.TOUR ->
            "Everything on this screen, where it actually is. " +
                "Press ${SelectorShortcut.SHORTCUTS.input} at any time to see it again."
    }

    /** "copies" / "moves", for naming the verb the user did *not* configure. */
    private fun thirdPerson(action: FilingAction): String = when (action) {
        FilingAction.COPY -> "copies"
        FilingAction.MOVE -> "moves"
    }
}
